# Generated by Django 5.0.7 on 2024-07-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
