# Generated by Django 5.0.7 on 2024-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium'),
        ),
    ]
